let editing=null,imageUrl='',items=[],previewUrl='',stockProducts=[],inventory={};
const form=document.getElementById('product-form'),status=document.getElementById('save-status');
async function api(url,options){const response=await fetch(url,options);let data;try{data=await response.json()}catch{throw Error('De server reageerde niet goed. Probeer opnieuw.')}if(!response.ok)throw Error(data.error||'De aanvraag is mislukt.');return data;}
async function load(){const data=await api('/api/catalog?admin=1',{cache:'no-store'});items=data.products;inventory=data.inventory||{};stockProducts=[...(data.baseProducts||[]).map(p=>({...p,isConcept:true})),...items];const list=document.getElementById('admin-products');list.replaceChildren();if(!items.length){const p=document.createElement('p');p.textContent='Je hebt nog geen eigen producten. Voeg je eerste product toe met het formulier.';list.append(p)}items.forEach(p=>{const row=document.createElement('article');row.className='admin-product';if(p.image){const img=document.createElement('img');img.src=p.image;img.alt=p.name;row.append(img)}const details=document.createElement('div'),name=document.createElement('h3'),info=document.createElement('p'),edit=document.createElement('button');name.textContent=p.name;info.textContent=new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(p.price/100)+' · '+(p.archived?'Verborgen':'Zichtbaar');edit.textContent='Bewerken';edit.className='button';edit.onclick=()=>editProduct(p);details.append(name,info,edit);row.append(details);list.append(row)});renderInventory();}
function inventoryText(p){const stock=inventory[p.id];return Number.isInteger(stock)&&stock>=0?(stock===0?'Uitverkocht':'Nog '+stock+' op voorraad'):(p.isConcept?'Voorraad nog niet bevestigd':'Voorraad nog niet opgegeven');}
function renderInventory(){
const list=document.getElementById('inventory-products'),query=document.getElementById('inventory-search').value.trim().toLocaleLowerCase('nl');list.replaceChildren();
const visible=stockProducts.filter(p=>[p.name,p.category].join(' ').toLocaleLowerCase('nl').includes(query));document.getElementById('inventory-count').textContent=visible.length+' producten';
if(!visible.length){const empty=document.createElement('p');empty.textContent='Geen producten gevonden. Probeer een andere zoekterm.';list.append(empty);return;}
visible.forEach(p=>{
const row=document.createElement('form');row.className='inventory-row';
if(p.image){const photo=document.createElement('img');photo.src=p.image;photo.alt=p.name;photo.loading='lazy';row.append(photo);}
const details=document.createElement('div');details.className='inventory-details';const name=document.createElement('h3');name.textContent=p.name;
const kind=document.createElement('p');kind.className='inventory-kind';kind.textContent=p.isConcept?'REVE-ontwerpconcept':(p.archived?'Eigen product · verborgen':'Eigen product');
const current=document.createElement('p');current.className='inventory-current';current.textContent=inventoryText(p);details.append(name,kind,current);row.append(details);
const controls=document.createElement('div');controls.className='inventory-controls';const label=document.createElement('label');label.textContent='Totaal over alle maten';
const input=document.createElement('input');input.name='stock';input.type='number';input.min='0';input.max='1000000';input.step='1';input.inputMode='numeric';input.placeholder='Echt aantal, bijv. 18';input.setAttribute('aria-label','Totale voorraad voor '+p.name);input.value=Number.isInteger(inventory[p.id])?String(inventory[p.id]):'';label.append(input);
const save=document.createElement('button');save.type='submit';save.className='button dark';save.textContent='Voorraad opslaan';
const message=document.createElement('p');message.className='inventory-save-status';message.setAttribute('role','status');controls.append(label,save,message);row.append(controls);
row.onsubmit=async event=>{event.preventDefault();const raw=input.value.trim();if(raw!==''&&(!/^\d+$/.test(raw)||Number(raw)>1000000)){message.textContent='Vul een heel aantal van 0 tot 1000000 in, of laat het veld leeg.';input.focus();return;}
const stock=raw===''?null:Number(raw);save.disabled=true;message.textContent='Voorraad opslaan…';try{const result=await api('/api/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'stock',id:p.id,stock})});if(result.stock===null)delete inventory[p.id];else inventory[p.id]=result.stock;input.value=result.stock===null?'':String(result.stock);current.textContent=inventoryText(p);message.textContent=result.stock===null?'Opgeslagen. De winkel toont geen aantal.':'Opgeslagen. Vernieuw de winkelpagina om het aantal te zien.';}catch(error){message.textContent=error.message;}finally{save.disabled=false;}};
list.append(row);
});
}
document.getElementById('inventory-search').addEventListener('input',renderInventory);
function reset(){form.reset();editing=null;imageUrl='';document.getElementById('photo-preview').hidden=true;document.getElementById('form-title').textContent='Nieuw product';status.textContent='';updateSizes();}
function updateSizes(){const category=form.elements.category.value,child=['jongens','meisjes'].includes(form.elements.audience.value);const clothing=!['accessoires','petjes','schoenen'].includes(category);document.getElementById('size-options').hidden=!clothing;document.getElementById('shoe-options').hidden=category!=='schoenen';const box=document.getElementById(category==='schoenen'?'shoe-options':'size-options');const options=category==='schoenen'?(child?['28','29','30','31','32','33','34','35']:['36','37','38','39','40','41','42','43','44','45','46']):(child?['116','122','128','134','140','146','152','158','164','170']:['XS','S','M','L','XL']);const name=category==='schoenen'?'shoe-sizes':'sizes';box.innerHTML='<legend>Beschikbare '+(category==='schoenen'?'schoenmaten':'maten')+'</legend>'+options.map(s=>'<label><input type="checkbox" name="'+name+'" value="'+s+'" checked> '+s+'</label>').join('');}

function editProduct(p){reset();editing=p.id;imageUrl=p.image;['name','color','description','category'].forEach(key=>form.elements[key].value=p[key]);form.elements.audience.value=p.audience||'unisex';updateSizes();form.elements.price.value=(p.price/100).toFixed(2);form.elements.archived.checked=p.archived;form.querySelectorAll('[name=sizes], [name=shoe-sizes]').forEach(el=>el.checked=p.sizes.includes(el.value));const preview=document.getElementById('photo-preview');if(p.image){preview.src=p.image;preview.hidden=false}document.getElementById('form-title').textContent='Product bewerken';form.scrollIntoView({behavior:'smooth'});form.elements.name.focus();}
document.getElementById('photo').onchange=()=>{const file=document.getElementById('photo').files[0],preview=document.getElementById('photo-preview');if(previewUrl)URL.revokeObjectURL(previewUrl);if(file){if(file.size>8*1024*1024){status.textContent='Foto te groot. Kies maximaal 8 MB.';document.getElementById('photo').value='';return}previewUrl=URL.createObjectURL(file);preview.src=previewUrl;preview.hidden=false;}else{preview.hidden=!imageUrl;if(imageUrl)preview.src=imageUrl}};
form.elements.category.onchange=updateSizes;form.elements.audience.onchange=updateSizes;document.getElementById('new-product').onclick=reset;
form.onsubmit=async(event)=>{event.preventDefault();const save=document.getElementById('save');save.disabled=true;try{const file=document.getElementById('photo').files[0];if(file){status.textContent='Foto uploaden…';const upload=new FormData();upload.append('file',file);imageUrl=(await api('/api/catalog',{method:'POST',body:upload})).url;}status.textContent='Product opslaan…';const payload={name:form.elements.name.value,color:form.elements.color.value,price:Math.round(Number(form.elements.price.value)*100),category:form.elements.category.value,audience:form.elements.audience.value,description:form.elements.description.value,image:imageUrl,archived:form.elements.archived.checked,sizes:Array.from(form.querySelectorAll(form.elements.category.value==='schoenen'?'[name=shoe-sizes]:checked':'[name=sizes]:checked')).map(el=>el.value)};if(editing)payload.id=editing;const data=await api('/api/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});editing=data.product.id;document.getElementById('photo').value='';status.textContent='Opgeslagen! Je wijziging staat in de winkel. Vernieuw de winkelpagina om hem te zien.';await load();}catch(error){status.textContent=error.message;}finally{save.disabled=false;}};
(async()=>{try{const me=await api('/api/catalog?me=1');if(!me.isOwner){document.getElementById('admin-status').textContent=me.authenticated?'Dit account heeft geen toegang tot het beheer. Gebruik het ChatGPT-account waarmee REVE is gemaakt.':'Alleen de eigenaar kan hier wijzigingen plaatsen. Log in met het ChatGPT-account waarmee REVE is gemaakt.';document.getElementById('admin-access').hidden=false;document.getElementById('admin-signin').hidden=me.authenticated;document.getElementById('admin-switch').hidden=!me.authenticated;return}document.getElementById('admin-status').textContent='Alleen jij hebt toegang tot dit beheer.';document.getElementById('workspace').hidden=false;await load();}catch(error){document.getElementById('admin-status').textContent=error.message;}})();
